name: Update blog posts
on:
  schedule: # Run workflow automatically
    - cron: '0 9 * * 1' # Runs at 09:00 on Monday.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in diegors.net posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://diegors.net/rss.xml"
